name: Build extension

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build
        run: |
          npm install
          npm run build:${{matrix.browser}}

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qtest-manager-assistant
          path: |
            dist/
            !dist/**/*.zip
          if-no-files-found: error
