name: Build with NodeJS and Webpack

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Build
        run: |
          npm install
          npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qtest-manager-assistant
          path: |
            dist/**/*.*
